services:
  mongo:
    image: mongo:latest
    container_name: qekms-mongodb
    restart: unless-stopped
    command: [ "mongod" ]
    ports:
      - "27018:27017"
    networks:
      - qekms-network
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: qekms-redis
    restart: unless-stopped
    command: [ "redis-server", "--save", "60", "1", "--loglevel", "warning" ]
    networks:
      - qekms-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # ✅ Backend (Live Reload)
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: qekms-backend:local
    container_name: qekms-backend
    working_dir: /app
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - qekms-network
    environment:
      - MONGODB_URL=mongodb://mongo:27017/qekms_db
      - DATABASE_NAME=qekms_db
      - SECRET_KEY=super_secure_key_123!
      - REDIS_URL=redis://redis:6379/0
      - EMAIL_LIST_VERIFY_API_KEY=RtW7plkWr9MF5gvRMFuZ5zVrzurGr9rO
    volumes:
      - .:/app
      - uploads_data:/app/uploads
      - logs_data:/app/logs
      - keys_data:/app/keys
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
  # ✅ Frontend (Hot Reload)
  frontend:
    image: node:18
    container_name: qekms-frontend
    working_dir: /app
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      backend:
        condition: service_started
    networks:
      - qekms-network
    volumes:
      - ./qekms-dashboard:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

networks:
  qekms-network:


volumes:
  mongo_data:
  uploads_data:
  logs_data:
  keys_data:
